#!/usr/bin/env node
// Session tooling. Git commits mark session start/end (the timestamps are the
// source of truth for time); token usage comes from Claude Code transcripts.
//
//   npm run session:start -- "Goal text" [--at 2026-10-04T16:07:55Z]
//   npm run session:status
//   npm run session:end [-- --at <iso> | --now]
//   npm run session:stats

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  activeMinutes,
  avgContext,
  fmtTokens,
  lastActivity,
  parseTimestamps,
  parseUsageRecords,
  projectSlug,
  summarizeUsage,
  totalTokens,
} from './usage.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const SESSIONS_DIR = path.join(ROOT, 'docs', 'sessions');
const STATS_JSON = path.join(SESSIONS_DIR, 'stats.json');
const STATS_MD = path.join(SESSIONS_DIR, 'STATS.md');
const TRAILER = '\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>';
const STALE_MINUTES = 30;
// Paths the end commit may stage. Never `git add -A`: the repo is also an Obsidian vault.
const END_PATHS = ['docs', 'CLAUDE.md', '.claude/skills'];
const SUBJECT_RE = /^session\((S\d+)\): (start|end)\b(?: — (.*))?$/;

const git = (args, env) =>
  execFileSync('git', args, {
    cwd: ROOT,
    encoding: 'utf8',
    env: { ...process.env, ...env },
    stdio: ['ignore', 'pipe', 'pipe'],
  }).trim();

// ---------- session discovery (from git) ----------

function sessionsFromGit() {
  let log = '';
  try {
    log = git(['log', '--reverse', '--format=%cI%x09%s']);
  } catch {
    return []; // no commits yet
  }
  const sessions = new Map();
  for (const line of log.split('\n')) {
    const [time, subject] = line.split('\t');
    const m = subject?.match(SUBJECT_RE);
    if (!m) continue;
    const [, id, kind, goal] = m;
    const s = sessions.get(id) ?? { id };
    if (kind === 'start') Object.assign(s, { start: time, goal });
    else s.end = time;
    sessions.set(id, s);
  }
  return [...sessions.values()];
}

const openSession = () => sessionsFromGit().find((s) => s.start && !s.end);

function nextId() {
  // Recorded stats count too, so numbering doesn't depend on git history alone.
  const nums = [...sessionsFromGit(), ...readStats()].map((s) => Number(s.id.slice(1)));
  const n = nums.length ? Math.max(...nums) + 1 : 1;
  return 'S' + String(n).padStart(2, '0');
}

// ---------- transcripts ----------

function transcriptFiles(sinceMs) {
  const dir =
    process.env.CLAUDE_TRANSCRIPTS_DIR ??
    path.join(os.homedir(), '.claude', 'projects', projectSlug(ROOT));
  if (!fs.existsSync(dir)) return [];
  const out = [];
  const walk = (d) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.jsonl') && fs.statSync(p).mtimeMs >= sinceMs) out.push(p);
    }
  };
  walk(dir);
  return out;
}

function measure(startIso, endMs = Date.now()) {
  const startMs = Date.parse(startIso);
  const records = [];
  const stamps = [];
  for (const f of transcriptFiles(startMs)) {
    const text = fs.readFileSync(f, 'utf8');
    records.push(...parseUsageRecords(text));
    stamps.push(...parseTimestamps(text));
  }
  const { total, byModel } = summarizeUsage(records, startMs, endMs);
  return {
    lastActivityMs: lastActivity(stamps, startMs, endMs),
    wallMinutes: Math.round((endMs - startMs) / 60_000),
    activeMinutes: activeMinutes(stamps, startMs, endMs),
    tokens: { ...total, total: totalTokens(total) },
    byModel,
  };
}

// ---------- stats files ----------

const readStats = () => (fs.existsSync(STATS_JSON) ? JSON.parse(fs.readFileSync(STATS_JSON, 'utf8')) : []);

function writeStatsMd(stats) {
  const sum = (k) => stats.reduce((a, s) => a + (k(s) ?? 0), 0);
  const row = (c) => `| ${c.join(' | ')} |`;
  const lines = [
    '# Session stats',
    '',
    '_Generated by `npm run session:stats` / `session:end` — do not edit by hand._',
    '',
    '- **Wall** = time between the git start/end commits.',
    '- **Active** = transcript activity, excluding idle gaps > 10 min.',
    '- **Tokens** = all model calls in this project during the session (incl. subagents). Cache reads are cheap; output is the expensive part.',
    '- **Ctx/call** = average context per call. Total ≈ calls × ctx/call, so both are worth keeping down.',
    '',
    row(['Session', 'Date', 'Goal', 'Wall', 'Active', 'Calls', 'Ctx/call', 'Input', 'Cache write', 'Cache read', 'Output', 'Total']),
    row(['---', '---', '---', '--:', '--:', '--:', '--:', '--:', '--:', '--:', '--:', '--:']),
    ...stats.map((s) =>
      row([
        `[${s.id}](${s.id}.md)`,
        s.start.slice(0, 10),
        s.goal ?? '',
        `${s.wallMinutes} min${s.note ? ' †' : ''}`,
        `${s.activeMinutes} min`,
        s.tokens.calls,
        fmtTokens(avgContext(s.tokens)),
        fmtTokens(s.tokens.input),
        fmtTokens(s.tokens.cacheWrite),
        fmtTokens(s.tokens.cacheRead),
        fmtTokens(s.tokens.output),
        fmtTokens(s.tokens.total),
      ]),
    ),
    row([
      '**Total**',
      '',
      `${stats.length} sessions`,
      `${sum((s) => s.wallMinutes)} min`,
      `${sum((s) => s.activeMinutes)} min`,
      sum((s) => s.tokens.calls),
      '',
      fmtTokens(sum((s) => s.tokens.input)),
      fmtTokens(sum((s) => s.tokens.cacheWrite)),
      fmtTokens(sum((s) => s.tokens.cacheRead)),
      fmtTokens(sum((s) => s.tokens.output)),
      fmtTokens(sum((s) => s.tokens.total)),
    ]),
    '',
    ...stats.filter((s) => s.note).map((s) => `† ${s.id}: ${s.note}
`),
  ];
  fs.writeFileSync(STATS_MD, lines.join('\n'));
}

function statsBlock(m) {
  const t = m.tokens;
  const models = Object.entries(m.byModel)
    .map(([k, v]) => `${k}: ${v.calls} calls, ${fmtTokens(totalTokens(v))}`)
    .join('; ');
  return [
    `- **Wall time:** ${m.wallMinutes} min (measured from the git start commit)`,
    `- **Active time:** ${m.activeMinutes} min`,
    `- **Tokens:** ${fmtTokens(t.total)} total — input ${fmtTokens(t.input)}, cache write ${fmtTokens(t.cacheWrite)}, cache read ${fmtTokens(t.cacheRead)}, output ${fmtTokens(t.output)} (${t.calls} calls, ${fmtTokens(avgContext(t))} context per call)`,
    `- **Models:** ${models || 'n/a'}`,
  ].join('\n');
}

// ---------- commands ----------

function takeAt(args) {
  const i = args.indexOf('--at');
  return i >= 0 ? new Date(args.splice(i, 2)[1]).toISOString() : null;
}

function cmdStart(args) {
  const at = takeAt(args);
  const goal = args.join(' ').trim();
  if (!goal) die('Usage: npm run session:start -- "Goal for this session"');
  const open = openSession();
  if (open) die(`${open.id} is still open (started ${open.start}). Run session:end first.`);

  const id = nextId();
  const date = (at ?? new Date().toISOString()).slice(0, 10);
  const file = path.join(SESSIONS_DIR, `${id}.md`);
  fs.mkdirSync(SESSIONS_DIR, { recursive: true });
  if (!fs.existsSync(file)) {
    const tpl = fs.readFileSync(path.join(SESSIONS_DIR, '_template.md'), 'utf8');
    fs.writeFileSync(file, tpl.replaceAll('{{ID}}', id).replaceAll('{{GOAL}}', goal).replaceAll('{{DATE}}', date));
  }
  git(['add', file]);
  const env = at ? { GIT_AUTHOR_DATE: at, GIT_COMMITTER_DATE: at } : {};
  git(['commit', '--allow-empty', '-m', `session(${id}): start — ${goal}${TRAILER}`], env);
  console.log(`Started ${id}: ${goal}\nLog: docs/sessions/${id}.md`);
}

function cmdStatus() {
  const open = openSession();
  if (!open) return console.log('No open session.');
  const m = measure(open.start);
  console.log(`${open.id} — ${open.goal}\n${statsBlock(m)}`);
  if (m.wallMinutes >= 50) console.log('\n⏰ ~1h budget nearly used — start wrapping up.');
}

function cmdEnd(args) {
  const open = openSession();
  if (!open) die('No open session to end.');
  const at = takeAt(args);
  const endMs = at ? Date.parse(at) : Date.now();
  const m = measure(open.start, endMs);
  // An end long after the last activity inflates wall time (S10: 441 min wall, 30 active).
  const idle = m.lastActivityMs === null ? 0 : (endMs - m.lastActivityMs) / 60_000;
  if (!at && !args.includes('--now') && idle > STALE_MINUTES) {
    const last = new Date(m.lastActivityMs).toISOString();
    die(
      `Last activity was ${Math.round(idle)} min ago (${last}).
` +
        `End at that time:  npm run session:end -- --at ${last}
` +
        `Or end now anyway: npm run session:end -- --now`,
    );
  }
  const { lastActivityMs, ...measured } = m;
  const entry = { id: open.id, goal: open.goal, start: open.start, end: new Date(endMs).toISOString(), ...measured };

  const stats = readStats().filter((s) => s.id !== open.id);
  stats.push(entry);
  fs.writeFileSync(STATS_JSON, JSON.stringify(stats, null, 2) + '\n');
  writeStatsMd(stats);

  const file = path.join(SESSIONS_DIR, `${open.id}.md`);
  if (fs.existsSync(file)) {
    const md = fs.readFileSync(file, 'utf8');
    fs.writeFileSync(
      file,
      md.replace(/<!-- stats:start -->[\s\S]*?<!-- stats:end -->/, `<!-- stats:start -->\n${statsBlock(m)}\n<!-- stats:end -->`),
    );
  }
  git(['add', '--', ...END_PATHS.filter((p) => fs.existsSync(path.join(ROOT, p)))]);
  const env = at ? { GIT_AUTHOR_DATE: at, GIT_COMMITTER_DATE: at } : {};
  git(['commit', '-m', `session(${open.id}): end — ${m.activeMinutes} min active, ${fmtTokens(m.tokens.total)} tokens${TRAILER}`], env);
  console.log(`Ended ${open.id}\n${statsBlock(m)}`);
}

function cmdStats() {
  const stats = readStats();
  writeStatsMd(stats);
  console.log(fs.readFileSync(STATS_MD, 'utf8'));
}

function die(msg) {
  console.error(msg);
  process.exit(1);
}

const [cmd, ...rest] = process.argv.slice(2);
const commands = { start: cmdStart, status: cmdStatus, end: cmdEnd, stats: cmdStats };
if (!commands[cmd]) die(`Unknown command "${cmd ?? ''}". Use: ${Object.keys(commands).join(', ')}`);
commands[cmd](rest);
